SET QUOTED_IDENTIFIER ON


DROP TABLE IF EXISTS #TEMP
SELECT assess_id,std_rap_id,response_code
,ID =IDENTITY(INT,1,1)
INTO #TEMP
FROM [dbo].as_rap_profile_response
WHERE response IS NULL

DECLARE @BATCH_SIZE INT =1000
DECLARE @NO_OF_REC INT 
DECLARE @NO_REC_PROCESSED INT =0
DECLARE @msg VARCHAR(500)
SELECT @NO_OF_REC=MAX(ID) FROM #TEMP

IF @BATCH_SIZE>@NO_OF_REC
BEGIN
SET @BATCH_SIZE=@NO_OF_REC
END 

WHILE (@NO_REC_PROCESSED<=@NO_OF_REC)
BEGIN

--SELECT ID 
UPDATE B
SET response=''
FROM #TEMP A
INNER JOIN  [dbo].as_rap_profile_response B ON B.assess_id=A.assess_id
AND B.std_rap_id=A.std_rap_id AND B.response_code=A.response_code
WHERE ID>=@NO_REC_PROCESSED
AND ID <@NO_REC_PROCESSED+@BATCH_SIZE

SET @msg = CONCAT(@NO_REC_PROCESSED+@@ROWCOUNT,' records processed out of ',@NO_OF_REC)
RAISERROR (@msg, 0, 1) WITH NOWAIT

SET @NO_REC_PROCESSED+=@BATCH_SIZE
PRINT(@NO_REC_PROCESSED)
END 

