
exec [operational].[sproc_facacq_autopre_RemoveTableFromDataCopy] 'as_service_change_detail'
exec [operational].[sproc_facacq_autopre_RemoveTableFromDataCopy] 'as_service_change_detail_audit'

exec [operational].[sproc_facacq_autopre_RemoveTableFromDataCopy] 'as_service_change_notification_service_level_snapshot'